<?php

namespace Dinushchathurya\Hospital;

class Hospital{
	
	public static function getProvinces(){
        return array_keys(self::$Hospital);
    }

    public static function getDistricts($hospital){
        return array_keys(self::$Hospital[$hospital]);
    }

    public static function getHospitals($authority){
        foreach(self::$Hospital as $hospital => $curAuthority){
            if(in_array($authority,array_keys($curAuthority))){
                return $curAuthority[$authority];
            }
        }
    }

    public static $Hospital = array(
        
        'Western' => array(
            'Colombo' =>
                array(
                    'National Hospital of Sri Lanka',
                    'Castle Street Hospital for Women, Colombo',
                    'Colombo South Teaching Hospital, Kalubowila',
                    'Dental Institute, Colombo',
                    'De Soysa Hospital for Women (De Soysa Maternity Hospital), Colombo',
                    'Lady Ridgeway Hospital for Children, Colombo',
                    'National Cancer Institute, Maharagama',
                    'National Eye Hospital, Colombo',
                    'National Institute of Mental Health (Angoda Mental Hospital), Angoda',
                    'Sri Jayawardenepura General Hospital, Sri Jayawardenepura',
                    'Infectious Disease Hospital (Fever Hospital), Angoda',
                    'Mulleriyawa Base Hospital (Colombo East General Hospital), Mulleriyawa',
                    'Avissawella Base Hospital, Avissawella',
                    'Homagama Base Hospital, Homagama',
                    'Piliyandala Divisional Hospital, Piliyandala',
                    'Wetara District Hospital, Polgasowita',
                    'Koswatta Divisional Hospital, Thalangama',
                    'Moratuwa District Hospital, Moratuwa',
                    'Padukka Divisional Hospital, Padukka',
                    'Maligawatta District Hospital (Premadasa Memorial Hospital), Maligawatta',
                    'Kosgama Divisional Hospital, Salawa',
                ),

            'Gampaha' =>
                array(
                    'Colombo North Teaching Hospital, Ragama',
                    'National Hospital for Respiratory Diseases (Welisara Chest Hospital), Welisara',
                    'Rheumtology and Rehabilitation Hospital, Ragama',
                    'andana Divisional Hospital, Kandana',
                    'Vijaya Kumaratunga Memorial Hospital, Seeduwa',
                    'Gampaha District General Hospital, Gampaha',
                    'Negombo District General Hospital (Negombo Base Hospital), Negombo',
                    'Wathupitiwala Base Hospital, Wathupitiwala',
                    'Kiribathgoda District Hospital, Kelaniya',
                    'Mirigama Base Hospital, Mirigama',
                    'Divulapitiya Divisional Hospital, Divulapitiya',
                    'Dompe Divisional Hospital, Dompe',
                    'Minuwangoda Divisional Hospital, Minuwangoda',
                    'Radawana Divisional Hospital, Radawana',
                    'Akaragama Divisional Hospital, Akaragama',
                    'Ja-Ela Divisional Hospital, Ja-Ela',
                    'Pamunugama Divisional Hospital, Pamunugama',
                ),

            'Kalutara' =>
                array(
                    'Kalutara District General Hospital, Kalutara',
                    'Beruwala Divisional Hospital, Beruwala',
                    'Dharga Town Divisional Hospital, Dharga Town',
                    'Horana Base Hospital, Horana',
                    'Panadura Base Hospital, Panadura',
                    'Agalawatta Base Hospital, Pimbura',
                    'Bandaragama Divisional Hospital, Bandaragama',
                    'BIngiriya Divisional Hospital, Ingiriya',
                    'Matugama Divisional Hospital, Matugama',
                    'Baduraliya Divisional Hospital, Baduraliya',
                    'Bulathsinhala Divisional Hospital, Bulathsinhala',
                    'Ittepana Divisional Hospital, Ittepana',
                    'Meegahatenne Divisional Hospital',
                    'Gonaduwa Divisional Hospital, Morontuduwa',
                ),
        ),

        'North Western' => array(
            'Kurunegala' =>
                array(
                    'Kurunegala Teaching Hospital, Kurunegala',
                    'Kuliyapitiya Teaching Hospital, Kuliyapitiya',
                    'Alawwa Hospital, Alawwa',
                    'Galgamuwa Hospital, Galgamuwa',
                    'Maho Hospital, Maho',
                    'Narammala Hospital, Narammala',
                    'Nickaweratiya Hospital, Nikaweratiya',
                    'Polgahawela Hospital, Polgahawela',
                    'Warialpola Hospital, Wariyapola',
                ),

            'Puttalam' =>
                array(
                    'Chilaw General Hospital',
                    'Base Hospital(A), Puttalam',
                    'Base hospital(B), Marawila',
                    'Divisional Hospital, Kalpitiya',
                    'Divisional Hospital, Dankotuwa',
                    'Divisional Hospital, Anamaduwa',
                ),
        ),

        'Central' => array(
            'Kandy' =>
                array(
                    'National Hospital (Teaching), Kandy',
                    'Sirimavo Bandaranayake Specialized Children Hospital (Teaching), Peradeniya',
                    'General Hospital (Teaching), Peradeniya',
                    'Base Hospital (Teaching) Gampola',
                    'Nawalapitiya District General Hoaspital Nawalapitiya - Nawalapitiya',
                    'Theldeniya District General Hospital- Theldeniya',
                ),

            'Nuwara Eliya' =>
                array(
                    'Nuwara Eliya District General Hospital - Nuwara Eliya',
                    'Agarapatana Divisional Hospital - Agarapatana',
                    'Bogawantalawa Divisional Hospital - Bogawantalawa',
                    'Dayagama Divisional Hospital - Dayagama',
                    'Ginigathhena Divisional Hospital - Ginigathhena', 
                    'Gonagastenna Divisional Hospital -Gonagastenna',
                    'Gonapitiya Divisional Hospital - Gonapitiya', 
                    'Hanguranketha Divisional Hospital - Hanguranketha', 
                    'Hiporest/ Gonakele Divisional Hospital- Hiporest/ Gonakele', 
                    'Kadapola Divisional Hospital - Kadapola', 
                    'Kotagala Divisional Hospital - Kotagala', 
                    'Kothmale Divisional Hospital - Kothmale',
                    'Lindula Divisional Hospital - Lindula', 
                    'Luxapana Divisional Hospital - Luxapana', 
                    'Madulla Divisional Hospital - Madulla', 
                    'Maldeniya Divisional Hospital - Maldeniya', 
                    'Mandaramnuwara Divisional Hospital -Mandaramnuwara',
                    'Maskeliya Divisional Hospital - Maskeliya', 
                    'Maturata Divisional Hospital - Maturata', 
                    'Mooloya Divisional Hospital - Mooloya', 
                    'Nildandahinna Divisional Hospital - Nildandahinna', 
                    'Theripaha Divisional Hospital - Theripaha',
                    'Udapussellawa Divisional Hospital - Udapussellawa',
                    'Walapane Divisional Hospital - Walapane',
                    'Watawala Divisional Hospital - Watawala',
                ),
        ),

        'Uva' => array(
            'Badulla' =>
                array(
                    'Badulla Provincial General Hospital - Badulla',
                    'Diyatalawa Base Hospital - Diyathalawa',
                    'Mahiyanganaya Base Hospital - Mahiyanganaya',
                    'Welimada Base Hospital - Welimada',
                    'Attampitiya Divisional Hospital - Attampitiya',
                    'Bandarawela Divisional Hospital - Bandarawela',
                    'Bibelagama Divisional Hospital - Bibelagama',
                    'Bogahakubura Divisional Hospital - Bogahakubura',
                    'Boralanda Divisional Hospital - Boralanda',
                    'Dambana Divisional Hospital - Dambana',
                    'Dambethanna Divisional Hospital - Dambethanna',
                    'Demodara Divisional Hospital - Demodara',
                    'Downside Divisional Hospital - Downside',
                    'Ekiriyankumbura Divisional Hospital - Ekiriyankumbura',
                    'Galauda Divisional Hospital - Galauda',
                    'Girandurukotte Divisional Hospital - Girandurukotte',
                    'Glennor Divisional Hospital - Glennor',
                    'Hakgala Divisional Hospital - Hakgala',
                    'Haldummulla Divisional Hospital - Haldummulla',
                    'Haputale Divisional Hospital - Haputale',
                    'Hoptan Divisional Hospital - Hoptan',
                    'Kahataruppa Divisional Hospital - Kahataruppa',
                    'Kandagolla Divisional Hospital - Kandagolla',
                    'Kandaketiya Divisional Hospital - Kandaketiya',
                    'Hoptan Divisional Hospital - Hoptan',
                    'Kandegedara Divisional Hospital - Kandegedara',
                    'Karavanella Divisional Hospital - Karavanella',
                    'Koslanda Divisional Hospital - Koslanda',
                    'Kurkeels Divisional Hospital - Kurkeels',
                    'Lunugala Divisional Hospital - Lunugala',
                    'Matigahatenna Divisional Hospital - Matigahatenna',
                    'Meedumpitiya Divisional Hospital - Meedumpitiya',
                    'Meegahakiula Divisional Hospital - Meegahakiula',
                    'Mirahawatta Divisional Hospital - Mirahawatta',
                    'Nadungamuwa Divisional Hospital - Nadungamuwa',
                    'Passara Divisional Hospital - Passara',
                    'Roberry Divisional Hospital - Roberry',
                    'Saraniya Divisional Hospital - Saraniya',
                    'Springvally Divisional Hospital - Springvally',
                    'Udaweriya Divisional Hospital - Udaweriya',
                    'Unugolla Divisional Hospital - Unugolla',
                    'Uraniya Divisional Hospital - Uraniya',
                    'Ury Divisional Hospital - Ury',
                    'Uva Highland Divisional Hospital',
                    'Uva Paranagame Divisional Hospital',
                    'Wewegama Divisional Hospital - Wewegama',
                ),

            'Monaragala' =>
                array(
                    'Monaragala District General Hospital - Monaragala',
                    'Bibile Base Hospital - Bibile',
                    'Badalkumbura Divisional Hospital - Badalkumbura',
                    'Buttala Divisional Hospital - Buttala',
                    'Dambagalla Divisional Hospital - Dambagalla',
                    'Ethimoie Divisional Hospital - Ethimoie',
                    'Hambegamuwa Divisional Hospital - Hambegamuwa',
                    'Handapanagala Divisional Hospital - Handapanagala',
                    'Hingurukaduwa Divisional Hospital - Hingurukaduwa',
                    'Inginiyagala Divisional Hospital - Inginiyagala',
                    'Kataragama Divisional Hospital - Kataragama',
                    'Madagama Divisional Hospital - Madagama',
                    'Okkampitiya Divisional Hospital - Okkampitiya',
                    'Pitakumbura Divisional Hospital - Pitakumbura',
                    'Sewanagala Divisional Hospital - Sewanagala',
                    'Siyambalanduwa Divisional Hospital - Siyambalanduwa',
                    'Thanamalwila Divisional Hospital - Thanamalwila',
                    'Wellawaya Divisional Hospital - Wellawaya',
                ),
        ),

        'Southern' => array(
            'Galle' =>
                array(
                    'Karapitiya Teaching Hospital - Karapitiya',
                    'Mahamodera Teaching Hospital - Mahamodera',
                    'Balapitiya Base Hospital - Balapitiya',
                    'Elpitiya Base Hospital - Elpitiya',
                    'Udugama Base Hospital - Udugama',
                    'Ahangama Divisional Hospital - Ahangama',
                    'Aluththanayamgoda Divisional Hospital - Aluththanayamgoda',
                    'Ambalangoda Divisional Hospital - Ambalangoda',
                    'Baddegama Divisional Hospital - Baddegama',
                    'Bentota Divisional Hospital - Bentota',
                    'Batapola Divisional Hospital - Batapola',
                    'Dellawa Divisional Hospital - Dellawa',
                    'Habaraduwa Divisional Hospital - Habaraduwa',
                    'Haburugala Divisional Hospital - Haburugala',
                    'Hikkaduwa Divisional Hospital - Hikkaduwa',
                    'Hiniduma Divisional Hospital - Hiniduma',
                    'Imaduwa Divisional Hospital - Imaduwa',
                    'Induruwa Divisional Hospital - Induruwa',
                    'Karandeniya Divisional Hospital - Karandeniya',
                    'Madampagama/Kuleegoda Divisional Hospital',
                    'Maternity Home Amugoda - Amugoda',
                    'Nagoda Divisional Hospital - Nagoda',
                    'Nelluwa Divisional Hospital - Nelluwa',
                    'Niyagama/ Thalgaswela Divisional Hospital',
                    'Thalapitiya Divisional Hospital - Thalapitiya',
                    'Unawatuna  Divisional Hospital - Unawatuna',
                    'Uragasmanhandiya Divisional Hospital - Uragasmanhandiya',
                    'Wanduramba  Divisional Hospital - Wanduramba',
                ),

            'Matara' =>
                array(
                    'Matara District General Hospital - Matara',
                    'Deniyaya Base Hospital - Deniyaya',
                    'Kamburupitiya Base Hospital - Kamburupitiya',
                    'Akuressa Divisional Hospital - Akuressa',
                    'Deiyandara Divisional Hospital - Deiyandara',
                    'Diekwella Divisional Hospital - Diekwella',
                    'Gangodagama Divisional Hospital - Gangodagama',
                    'Kirinda Divisional Hospital - Kirinda',
                    'Mawarala Divisional Hospital - Mawarala',
                    'Midigama Divisional Hospital - Midigama',
                    'Morawaka Divisional Hospital - Morawaka',
                    'Narawalpita Divisional Hospital - Narawalpita',
                    'Pallegama Divisional Hospital - Pallegama',
                    'Ruhunugama Divisional Hospital - Ruhunugama',
                    'Thalalla Divisional Hospital - Thalalla',
                    'Urubokka Divisional Hospital - Urubokka',
                    'Urugamuwa Divisional Hospital - Urugamuwa',
                    'Weligama Divisional Hospital - Weligama',
                ),

            'Hambantota' =>
                array(
                    'Hambantota District General Hospital - Hambantota',
                    'Tangalle Base Hospital - Tangalle',
                    'Walasmulla Base Hospital - Walasmulla', 
                    'Ambalanthota Divisional Hospital - Ambalanthota', 
                    'Angunakolapalessa Divisional Hospital - Angunakolapalessa', 
                    'Beliatta Divisional Hospital - Beliatta', 
                    'Beragama Divisional Hospital - Beragama', 
                    'Getamanna Divisional Hospital - Getamanna', 
                    'Gonadeniya Divisional Hospital - Gonadeniya', 
                    'Hakuruwela Divisional Hospital - Hakuruwela',
                    'Ihalabeligalla Divisional Hospital - Ihalabeligalla', 
                    'Kariyamadittha Divisional Hospital - Kariyamadittha', 
                    'Katuwana Divisional Hospital - Katuwana', 
                    'Kirima Divisional Hospital - Kirima', 
                    'Kirinda Divisional Hospital - Kirinda', 
                    'Ihalabeligalla Divisional Hospital - Ihalabeligalla', 
                    'Kariyamadittha Divisional Hospital - Kariyamadittha', 
                    'Katuwana Divisional Hospital - Katuwana', 
                    'Kirima Divisional Hospital - Kirima', 
                    'Kirinda Divisional Hospital - Kirinda', 
                    'Middeniya Divisional Hospital, Middeniya',
                    'Nakulugamuwa Divisional Hospital - Nakulugamuwa', 
                    'Ranna Divisional Hospital - Ranna', 
                    'Sooriyawewa Divisional Hospital - Sooriyawewa', 
                    'Uduwila Divisional Hospital - Uduwila', 
                    'Weeraketiya Divisional Hospital, Weeraketiya',
                    'Wilamulla Divisional Hospital, Wilamulla',   
                ),
        ),

        'Sabaragamuwa' => array(
            'Ratnapura' =>
                array(
                    'Ratnapura Provincial General Hospital - Ratnapura',
                    'Balangoda Base Hospital - Balangoda',
                    'Embilipitiya Base Hospital - Embilipitiya',
                    'Kahawatta Base Hospital - Kahawatta',
                    'Kalawana Base Hospital - Kalawana', 
                    'Alupola Divisional Hospital - Alupola', 
                    'Ayagama Divisional Hospital - Ayagama', 
                    'Belihuloya Divisional Hospital - Belihuloya', 
                    'Chandrikawewa Divisional Hospital - Chandrikawewa', 
                    'Eheliyagoda Divisional Hospital - Eheliyagoda', 
                    'Endana Divisional Hospital - Endana', 
                    'Erathna Divisional Hospital - Erathna',
                    'Gallella Divisional Hospital - Gallella', 
                    'Gilimale Divisional Hospital - Gilimale', 
                    'Godakawela Divisional Hospital - Godakawela', 
                    'Hunuwala Divisional Hospital - Hunuwala', 
                    'Kaltota Divisional Hospital - Kaltota', 
                    'Kiribathgala Divisional Hospital - Kiribathgala', 
                    'Kiriella Divisional Hospital - Kiriella', 
                    'Kiriporuwa Divisional Hospital - Kiriporuwa', 
                    'Kolonna Divisional Hospital - Kolonna', 
                    'Mahawalatenna Divisional Hospital - Mahawalatenna', 
                    'Maratenne Divisional Hospital, Maratenne',
                    'Nivitigala Divisional Hospital - Nivitigala', 
                    'Pallebedda Divisional Hospital - Pallebedda', 
                    'Pelmadulla Divisional Hospital - Pelmadulla', 
                    'Pothupitiya Divisional Hospital - Pothupitiya', 
                    'Rakwana Divisional Hospital, Rakwana',
                    'Ranwala Divisional Hospital, Ranwala',
                    'Sooriyakanda Divisional Hospital - Sooriyakanda', 
                    'Teppanawa Divisional Hospital - Teppanawa', 
                    'Udawalawa Divisional Hospital - Udawalawa', 
                    'Weligepola Divisional Hospital - Weligepola', 
                ),

            'Kegalle' =>
                array(
                    'Kegalle District General Hospital - Kegalle',
                    'Karawanella Base Hospital - Karawanella',
                    'Mawanella Base Hospital - Mawanella', 
                    'Warakapola Base Hospital - Warakapola', 
                    'Algama Divisional Hospital - Algama', 
                    'Amanawala Divisional Hospital - Amanawala', 
                    'Amitirigala Divisional Hospital - Amitirigala', 
                    'Aranayaka Divisional Hospital - Aranayaka', 
                    'Atala Divisional Hospital - Atala', 
                    'Beligala Divisional Hospital - Beligala', 
                    'Bulathkohupitiya Divisional Hospital - Bulathkohupitiya',
                    'Dedugala Divisional Hospital - Dedugala', 
                    'Dematanpitiya MRC Divisional Hospital - Dematanpitiya MRC', 
                    'Dvulankadawela Divisional Hospital - Dvulankadawela', 
                    'ERH Kiriporuwa Divisional Hospital - ERH Kiriporuwa',
                    'Gonagaldeniya Divisional Hospital - Gonagaldeniya', 
                    'Halgolla Divisional Hospital - Halgolla', 
                    'Hemmathagama Divisional Hospital - Hemmathagama',
                    'Hinguralakanda Divisional Hospital - Hinguralakanda',
                    'Kithulgala Divisional Hospital - Kithulgala', 
                    'Mahapallegama Divisional Hospital - Mahapallegama',
                    'Deraniyagala Divisional Hospital - Deraniyagala',
                    'Malimboda Divisional Hospital - Malimboda',
                    'Mulendiyawala Divisional Hospital - Mulendiyawala',
                    'Rambukkana Divisional Hospital - Rambukkana',
                    'Sapumalkanda Divisional Hospital - Sapumalkanda',
                    'Wakirigala Divisional Hospital - Wakirigala',
                ),
        ),

        'North Central' => array(
            'Anuradhapura' =>
                array(
                    'Anuradhapura Teaching Hospital - Anuradhapura',
                    'Kebithigollewa Base Hospital - Kebithigollewa',
                    'Padaviya Base Hospital - Padaviya', 
                    'Thambuththegama Base Hospital - Thambuththegama', 
                    'Andiyagala Divisional Hospital - Andiyagala', 
                    'Elayapaththuwa Divisional Hospital - Elayapaththuwa', 
                    'Eppawala Divisional Hospital - Eppawala', 
                    'Galenbindunuwewa Divisional Hospital - Galenbindunuwewa', 
                    'Galkiriyagama Divisional Hospital - Galkiriyagama', 
                    'Galkiriyagama Divisional Hospital - Galkiriyagama', 
                    'Galnewa Divisional Hospital - Galnewa',
                    'Gambirigaswewa Divisional Hospital - Gambirigaswewa', 
                    'Habarana Divisional Hospital - Habarana', 
                    'Horowpothana Divisional Hospital - Horowpothana', 
                    'Huruluwewa Divisional Hospital - Huruluwewa',
                    'Kahatagasdigiliya Divisional Hospital - Kahatagasdigiliya', 
                    'Kalawewa Divisional Hospital - Kalawewa', 
                    'Kallanchiya Divisional Hospital - Kallanchiya', 
                    'Kapugollewa Divisional Hospital - Kapugollewa', 
                    'Kattiyawa Divisional Hospital - Kattiyawa', 
                    'Kekirawa Divisional Hospital - Kekirawa',
                    'Labunoruwa Divisional Hospital - Labunoruwa', 
                    'Mahawilachchiya Divisional Hospital - Mahawilachchiya', 
                    'Maradankadawala Divisional Hospital - Maradankadawala', 
                    'Medawachchiya Divisional Hospital - Medawachchiya',
                    'Medawachchiya  Divisional Hospital - Medawachchiya ',
                    'Renal Unit Divisional Hospital - Renal Unit', 
                    'Mihinthale Divisional Hospital - Mihinthale', 
                    'Nachchaduwa Divisional Hospital - Nachchaduwa', 
                    'Negampha Divisional Hospital - Negampha', 
                    'Nelubewa Divisional Hospital - Nelubewa',
                    'Nochchiyagama Divisional Hospital - Nochchiyagama', 
                    'Pairamaduwa Divisional Hospital - Pairamaduwa', 
                    'Parasangaswewa Divisional Hospital - Parasangaswewa', 
                    'Poonewa Divisional Hospital - Poonewa',
                    'Rajanganaya Tr 11 Divisional Hospital - Rajanganaya Tr 11', 
                    'Rajanganaya Tr 5 Divisional Hospital - Rajanganaya Tr 5', 
                    'Rambewa Divisional Hospital - Rambewa', 
                    'Ranorawa Divisional Hospital - Ranorawa', 
                    'Rathmalgahawewa Divisional Hospital - Rathmalgahawewa',
                    'Sampathnuwara Divisional Hospital - Sampathnuwara', 
                    'Senapura Divisional Hospital - Senapura', 
                    'Thalawa Divisional Hospital - Thalawa', 
                    'Thammennawa Divisional Hospital - Thammennawa', 
                    'Thanthirimale Divisional Hospital - Thanthirimale', 
                    'Wahalkada Divisional Hospital - Wahalkada', 
                ),

            'Polonnaruwa' =>
                array(
                    'Polonnaruwa General Hospital - Polonnaruwa',
                    'Medirigiriya Base Hospital - Medirigiriya', 
                    'Walikanda Base Hospital - Walikanda', 
                    'Aralaganwila Divisional Hospital - Aralaganwila', 
                    'Attanakadawala Divisional Hospital - Attanakadawala', 
                    'Bakamuna Divisional Hospital - Bakamuna',
                    'Diyabeduma Divisional Hospital - Diyabeduma', 
                    'Galamuna Divisional Hospital - Galamuna', 
                    'Hingurakgoda Divisional Hospital - Hingurakgoda', 
                    'Jayanthipura Divisional Hospital - Jayanthipura',
                    'Manampitiya Divisional Hospital - Manampitiya',
                    'Pulasthigama Divisional Hospital - Pulasthigama', 
                ),
        ),

        'Northern' => array(
            'Jaffna' =>
                array(
                    'Jaffna Teaching Hospital - Jaffna', 
                    'Chavakachcheri Base Hospital - Chavakachcheri', 
                    'Kayts Base Hospital - Kayts', 
                    'Point Pedro Base Hospital - Point Pedro', 
                    'Tellippalai Base Hospital - Tellippalai', 
                    'Ampan Divisional Hospital - Ampan', 
                    'Alaveddy Divisional Hospital - Alaveddy', 
                    'Analaitivu Divisional Hospital - Analaitivu',
                    'Atchuvely Divisional Hospital - Atchuvely',
                    'Chankanai Divisional Hospital - Chankanai', 
                    'Delft Divisional Hospital - Delft', 
                    'Gurunagar Divisional Hospital - Gurunagar', 
                    'Karainagar Divisional Hospital - Karainagar', 
                    'Karaveddy Divisional Hospital - Karaveddy',
                    'Kodikamam Divisional Hospital - Kodikamam', 
                    'Kondavil Divisional Hospital - Kondavil', 
                    'Kopay Divisional Hospital - Kopay',
                    'Manipay Divisional Hospital - Manipay', 
                    'Maruthankerny Divisional Hospital - Maruthankerny', 
                    'Nainativu Divisional Hospital - Nainativu', 
                    'Pandatharippu Divisional Hospital - Pandatharippu',
                    'Pungudutivu Divisional Hospital - Pungudutivu',
                    'Vaddukoddai Divisional Hospital - Vaddukoddai', 
                    'Valvettithurai Divisional Hospital - Valvettithurai', 
                    'Varany Divisional Hospital - Varany',
                    'Velanai Divisional Hospital - Velanai', 
                ),

            'Kilinochchi' =>
                array(
                    'Kilinochchi District General Hospital - Kilinochchi',
                    'Akkarayankulam Divisional Hospital - Akkarayankulam', 
                    'Mulankavil Divisional Hospital - Mulankavil', 
                    'Pallai Divisional Hospital - Pallai', 
                    'Poonakary Divisional Hospital - Poonakary',
                    'Tharmapuram Divisional Hospital - Tharmapuram',
                    'Vaddakachchi Divisional Hospital - Vaddakachchi', 
                    'Veravil Divisional Hospital - Veravil', 
                ),
            'Mannar' =>
                array(
                    'Mannar District General Hospital - Mannar',
                    'Adampan Divisional Hospital - Adampan', 
                    'Chilawathurai Divisional Hospital - Chilawathurai', 
                    'Erukkalampiddy Divisional Hospital - Erukkalampiddy', 
                    'Murukkan Divisional Hospital - Murukkan',
                    'Nanattan Divisional Hospital - Nanattan',
                    'Periyapandivrichchan Divisional Hospital - Periyapandivrichchan', 
                    'Pesalai Divisional Hospital - Pesalai', 
                    'Talaimannar Divisional Hospital - Talaimannar', 
                    'Vankalai Divisional Hospital - Vankalai', 
                    'Vidathaltivu Divisional Hospital - Vidathaltivu',
                ),

            'Vavuniya' =>
                array(
                    'Vavuniya District General Hospital - Vavuniya',
                    'Cheddikulam Base Hospital - Cheddikulam', 
                    'Mamaduwa Divisional Hospital - Mamaduwa', 
                    'Nedunkerny Divisional Hospital - Nedunkerny', 
                    'Neriyakulam Divisional Hospital - Neriyakulam',
                    'Pampaimadu Divisional Hospital - Pampaimadu',
                    'Pavatkulam Divisional Hospital - Pavatkulam', 
                    'Poovarasanculam Divisional Hospital - Poovarasanculam', 
                    'Puliankulam Divisional Hospital - Puliankulam', 
                    'Sithamparapuram Divisional Hospital - Sithamparapuram', 
                    'Ulukkulam Divisional Hospital - Ulukkulam',
                ),
            
            'Mullaitivu' =>
                array(
                    'Mullaitivu District General Hospital - Mullaitivu',
                    'Mankulam Base Hospital - Mankulam', 
                    'Mallavi Divisional Hospital - Mallavi', 
                    'Naddankandal Divisional Hospital - Naddankandal', 
                ),
        ),

        'Eastern' => array(
            'Batticaloa' =>
                array(
                    'Batticaloa Teaching Hospital - Batticaloa',                    
                    'Valaichenai Divisional Hospital - Valaichenai', 
                    'Arayampathy Divisional Hospital - Arayampathy', 
                    'Chenkalady Divisional Hospital - Chenkalady', 
                    'Eravur Divisional Hospital - Eravur',
                    'Kallar Divisional Hospital - Kallar',
                    'Kaluwanchikudy Divisional Hospital - Kaluwanchikudy', 
                    'Karadiyanaru Divisional Hospital - Karadiyanaru', 
                    'Karthiravely Divisional Hospital - Karthiravely', 
                    'Kattankudy Divisional Hospital - Kattankudy', 
                    'Kokkaddicholai Divisional Hospital - Kokkaddicholai',
                    'Mandapathady Divisional Hospital - Mandapathady', 
                    'Mavadivembu Divisional Hospital - Mavadivembu', 
                    'Meeravodai Divisional Hospital - Meeravodai',
                    'Palamunai Divisional Hospital - Palamunai',
                    'Palukamam Divisional Hospital - Palukamam',
                    'Santhively Divisional Hospital - Santhively', 
                    'Thurailelavalai Divisional Hospital - Thurailelavalai',
                    'Vakarai Divisional Hospital - Vakarai',
                ),

            'Ampara' =>
                array(
                    'Ampara District General Hospital - Ampara',
                    'Dehiatthakandiya Base Hospital - Dehiatthakandiya',
                    'Mahaoya Base Hospital - Mahaoya',  
                    'Ambagahawella Divisional Hospital - Ambagahawella', 
                    'Namaloya Divisional Hospital - Namaloya', 
                    'Damana  Divisional Hospital - Damana ', 
                    'Panama Divisional Hospital - Panama',
                    'Kakuluwela Divisional Hospital - Kakuluwela',
                    'Pannalgama Divisional Hospital - Pannalgama', 
                    'Koknahara Divisional Hospital - Koknahara', 
                    'Paragahakale Divisional Hospital - Paragahakale', 
                    'Lahugala Divisional Hospital - Lahugala', 
                    'Senarathpura Divisional Hospital - Senarathpura',
                    'Madawalalanda Divisional Hospital - Madawalalanda', 
                    'Thottama Divisional Hospital - Thottama', 
                    'Mangalagama Divisional Hospital - Mangalagama',
                    'Wadinagala Divisional Hospital - Wadinagala', 
                    'Mawanawela Divisional Hospital - Mawanawela',   
                    'Weeragoda Divisional Hospital - Weeragoda', 
                ),
            
            'Trincomalee' =>
                array(
                    'Trincomalee District General Hospital - Trincomalee',
                    'Kanthalai Base Hospital - Kanthalai',
                    'Kinniya Base Hospital - Kinniya', 
                    'Muttur Base Hospital - Muttur',
                    'Gomarankadawala Divisional Hospital - Gomarankadawala', 
                    'Ichchilampathai Divisional Hospital - Ichchilampathai', 
                    'Kilivetti Divisional Hospital - Kilivetti', 
                    'Kuchchaveli Divisional Hospital - Kuchchaveli',
                    'Mahadivulwewa Divisional Hospital - Mahadivulwewa',
                    'Mahadivulwewa Divisional Hospital - Mahadivulwewa',
                    'Nilaveli Divisional Hospital - Nilaveli', 
                    'Padavisiripur Divisional Hospital - Padavisiripur', 
                    'Pulmoddai Divisional Hospital - Pulmoddai', 
                    'Serunuwara Divisional Hospital - Serunuwara', 
                    'Seruwila Divisional Hospital - Seruwila',
                    'Thampalagamam Divisional Hospital - Thampalagamam', 
                    'Thoppur Divisional Hospital - Thoppur', 
                    'Wan Ela Divisional Hospital - Wan Ela',  
                ),
        ),
    );
}
